### ISSUE TITLE
Cannot post comments in utterances

### ISSUE THREAD

**Issue by mcb00** [prrao87/blog#11]
I wanted to thank you for writing one of your posts, but when I try to post in utterances, I see this error message. I wonder if the utterances app is set up and configured correctly in this repo.

![Screen Shot 2021-01-27 at 18 24 34](https://user-images.githubusercontent.com/26044525/106081544-ee72df80-60cd-11eb-99dc-cfd0e283e292.png)

**Comment by prrao87** [comment]
Ah, thanks for pointing it out! I'd disabled utterances because I wanted people without GitHub accounts to also be able to comment, due to which I added Disqus. Now that I think about it, utterances makes sense. I've upgraded fastpages and have re-enabled utterances on this repo, so it should be working again. Thanks for reading and trying to comment! :)
